# Generated by Django 5.2 on 2025-04-25 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_choice_is_correct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='selected_choice',
            new_name='answer_choice',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='is_correct',
        ),
    ]
